//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDatabseView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StdId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> classId { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
